---
title: "Obtener los genes en comun up regulated y down regulated para datasets con CSC de cancer de mama y páncreas"
author: "Iván López-Baltasar"
date: "25/4/2020"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```
voy a obtener los genes comunes en los analisis de datasets de celulas madre de BC(GSE25976) y cancer de pancreas
(GSE51971). Se obtienen de los genes core enrichement para cada gene-list
```{r ficheros}
library(data.table)
library(tibble)

dirWork <- './data/work2/'

guardar_top_50 <- function (prefijo, rankedFich, dirWork){
  ranked <- read.csv(rankedFich,  sep="\t", header=TRUE, stringsAsFactors = FALSE)
  summary(ranked)
  ranked <- ranked[,1:3]
  summary(ranked)
  upregulated <- head(ranked,1000)
  downregulated <- tail(ranked,1000)
  
  write.csv(upregulated, paste(dirWork, prefijo, 'upregulated.csv',sep=""), row.names = F, quote = T,sep = '\t')
  write.csv(downregulated, paste(dirWork,prefijo, 'downregulated.csv',sep=""), row.names = F, quote = T,sep = '\t')
  result <- list(upregulated, downregulated)
}


#obtener los core enrichemnt
guardar_core <- function(prefijo, rankedFich, dirWork){
  ranked <- read.csv(rankedFich,  sep="\t", header=TRUE, stringsAsFactors = FALSE)
  ranked$CORE.ENRICHMENT <- as.factor(ranked$CORE.ENRICHMENT)
  enrichment <- ranked[ranked$CORE.ENRICHMENT=="Yes",]
  summary(enrichment)
  result <- enrichment
}


#TERCER DATASET BC GSE25976
dirGSEA_BCSC <- 'C:/Users/LOPEZBALTASI/gsea_home/output/nov22/BCSCs.Gsea.1606036652985/'
fichero <- paste(dirGSEA_BCSC,'ranked_gene_list_HIGH_METASTATIC_versus_MDA-MB-231_1606036652985.tsv', sep="")

#BCSC <- guardar_top_50("GSE25976-", fichero, dirWork)


#dataset GSE51971
dirGSEA_PC <- 'C:/Users/LOPEZBALTASI/gsea_home/output/nov22/PC_38_332_421.Gsea.1606035391916/'
fichero38 <- paste(dirGSEA_PC,'38-gene-list.grp.tsv', sep="")
fichero332 <- paste(dirGSEA_PC,'332-gene-list.grp.tsv', sep="")
fichero421 <- paste(dirGSEA_PC,'421-gene-list.grp.tsv', sep="")

down1 <- guardar_core("GSE51971-down", fichero38, dirWork)
down2 <- guardar_core("GSE51971-down", fichero332, dirWork)
up <- guardar_core("GSE51971-up", fichero421, dirWork)
head(up)


#PC_38_332_421 <- guardar_top_50("GSE51971-", fichero, dirWork)



```

